var menu='';
menu+='<a target="_parent" href="/"><h3>Home</h3></a>';
menu+='<a target="_parent" href="/posts/"><h3>Post List</h3></a>';
menu+='<ul>';
menu+='	<li><a target="_parent" href="/posts/A Trip of Konjac/">A Trip of Konjac</a></li>';
menu+='	<li><a target="_parent" href="/posts/About Me/">About Me</a></li>';
menu+='	<li><a target="_parent" href="/posts/Preface/">Preface</a></li>';
menu+='	<li><a target="_parent" href="/posts/The Story of the Chorus-I/">The Story of the Chorus-I</a></li>';
menu+='	<li><a target="_parent" href="/posts/The Story of the Chorus-II/">The Story of the Chorus-II</a></li>';
menu+='	<li><a target="_parent" href="/posts/The Story of the Chorus-III/">The Story of the Chorus-III</a></li>';
menu+='</ul>';
menu+='<a target="_parent" href="/codes/"><h3>Code List</h3></a>';
menu+='<ul>';
menu+='	<li><a target="_parent" href="/codes/BZOJ/1197.xml">BZOJ 1197</a></li>';
menu+='	<li><a target="_parent" href="/codes/BZOJ/4300.xml">BZOJ 4300</a></li>';
menu+='	<li><a target="_parent" href="/codes/HDU/1009.xml">HDU 1009</a></li>';
menu+='	<li><a target="_parent" href="/codes/HDU/1052.xml">HDU 1052</a></li>';
menu+='	<li><a target="_parent" href="/codes/HDU/2089.xml">HDU 2089</a></li>';
menu+='	<li><a target="_parent" href="/codes/HDU/2094.xml">HDU 2094</a></li>';
menu+='	<li><a target="_parent" href="/codes/HDU/2548.xml">HDU 2548</a></li>';
menu+='	<li><a target="_parent" href="/codes/NOIp/2004 PJT1.xml">NOIp 2004 PJT1</a></li>';
menu+='	<li><a target="_parent" href="/codes/NOIp/2004 PJT2.xml">NOIp 2004 PJT2</a></li>';
menu+='	<li><a target="_parent" href="/codes/NOIp/2004 PJT3.xml">NOIp 2004 PJT3</a></li>';
menu+='	<li><a target="_parent" href="/codes/NOIp/2004 PJT4.xml">NOIp 2004 PJT4</a></li>';
menu+='	<li><a target="_parent" href="/codes/NOIp/2004 TGT1.xml">NOIp 2004 TGT1</a></li>';
menu+='	<li><a target="_parent" href="/codes/NOIp/2004 TGT2.xml">NOIp 2004 TGT2</a></li>';
menu+='	<li><a target="_parent" href="/codes/NOIp/2004 TGT3.xml">NOIp 2004 TGT3</a></li>';
menu+='	<li><a target="_parent" href="/codes/NOIp/2005 PJT2.xml">NOIp 2005 PJT2</a></li>';
menu+='	<li><a target="_parent" href="/codes/NOIp/2005 PJT3.xml">NOIp 2005 PJT3</a></li>';
menu+='	<li><a target="_parent" href="/codes/NOIp/2005 TGT1.xml">NOIp 2005 TGT1</a></li>';
menu+='	<li><a target="_parent" href="/codes/NOIp/2011 TGT1.xml">NOIp 2011 TGT1</a></li>';
menu+='	<li><a target="_parent" href="/codes/NOIp/2011 TGT2.xml">NOIp 2011 TGT2</a></li>';
menu+='	<li><a target="_parent" href="/codes/NOIp/2011 TGT4.xml">NOIp 2011 TGT4</a></li>';
menu+='	<li><a target="_parent" href="/codes/NOIp/2012 PJT1.xml">NOIp 2012 PJT1</a></li>';
menu+='	<li><a target="_parent" href="/codes/NOIp/2012 TGT1.xml">NOIp 2012 TGT1</a></li>';
menu+='	<li><a target="_parent" href="/codes/NOIp/2015 PJT1.xml">NOIp 2015 PJT1</a></li>';
menu+='	<li><a target="_parent" href="/codes/NOIp/2015 PJT2.xml">NOIp 2015 PJT2</a></li>';
menu+='	<li><a target="_parent" href="/codes/NOIp/2015 TGT1.xml">NOIp 2015 TGT1</a></li>';
menu+='	<li><a target="_parent" href="/codes/NOIp/2016 PJT1.xml">NOIp 2016 PJT1</a></li>';
menu+='	<li><a target="_parent" href="/codes/NOIp/2016 PJT2.xml">NOIp 2016 PJT2</a></li>';
menu+='	<li><a target="_parent" href="/codes/NOIp/2016 PJT3.xml">NOIp 2016 PJT3</a></li>';
menu+='	<li><a target="_parent" href="/codes/NOIp/2016 TGT1.xml">NOIp 2016 TGT1</a></li>';
menu+='	<li><a target="_parent" href="/codes/NOIp/2016 TGT4.xml">NOIp 2016 TGT4</a></li>';
menu+='	<li><a target="_parent" href="/codes/POJ/1003.xml">POJ 1003</a></li>';
menu+='	<li><a target="_parent" href="/codes/POJ/1004.xml">POJ 1004</a></li>';
menu+='	<li><a target="_parent" href="/codes/POJ/1006.xml">POJ 1006</a></li>';
menu+='	<li><a target="_parent" href="/codes/POJ/1007.xml">POJ 1007</a></li>';
menu+='	<li><a target="_parent" href="/codes/POJ/1088.xml">POJ 1088</a></li>';
menu+='	<li><a target="_parent" href="/codes/POJ/2000.xml">POJ 2000</a></li>';
menu+='	<li><a target="_parent" href="/codes/POJ/2506.xml">POJ 2506</a></li>';
menu+='	<li><a target="_parent" href="/codes/POJ/2965.xml">POJ 2965</a></li>';
menu+='	<li><a target="_parent" href="/codes/POJ/3278.xml">POJ 3278</a></li>';
menu+='	<li><a target="_parent" href="/codes/POJ/3295.xml">POJ 3295</a></li>';
menu+='</ul>';
menu+='<h3>Friendly Link</h3>';
menu+='<ul>';
menu+='	<li>_|￣|○ <a target="_parent" href="http://blog.oceaneye.moe/">HFer_FDC</a></li>';
menu+='	<li>_|￣|○ <a target="_parent" href="https://www.cnblogs.com/yohanlong/">HFer_LHZ</a></li>';
menu+='	<li>_|￣|○ <a target="_parent" href="http://blog.csdn.net/haarmony/">HFer_MHX</a></li>';
menu+='	<li>_|￣|○ <a target="_parent" href="http://blog.eleele.gq/">HFer_WHJ</a></li>';
menu+='	<li>_|￣|○ <a target="_parent" href="https://code.del.moe/">HFer_ZFR</a></li>';
menu+='</ul>';
document.getElementById('menu').innerHTML=menu;
