<h1>CF 1182E</h1>
<p><time>2020-01-17 14:40</time> by zsz12251665</p>
<section>
	<h2>Problem</h2>
	<ul class="buttonList">
		<a target="_blank" href="https://vjudge.net/problem/CodeForces-1182E"><li>Virtual Judge</li></a>
		<a target="_blank" href="https://www.luogu.com.cn/problem/CF1182E"><li>Luogu</li></a>
		<a target="_blank" href="https://codeforces.com/problemset/problem/1182/E"><li>Codeforces</li></a>
	</ul>
</section>
<section>
	<h2>Solution</h2>
	<p>This problem is a combination of fast power and Fermat's little theorem. </p>
	<p>Firstly, we know that any <data value="v{f}b{v{n}}"></data> can be split into the product of several times of <data value="v{f}b{c{1}}"></data>, <data value="v{f}b{c{2}}"></data>, <data value="v{f}b{c{3}}"></data> and <data value="v{c}"></data>. This is because <data value="v{f}b{c{1}}o{=}v{c}p{c{0}}o{}v{f}b{c{1}}p{c{1}}o{}v{f}b{c{2}}p{c{0}}o{}v{f}b{c{3}}p{c{0}}"></data>, <data value="v{f}b{c{2}}o{=}v{c}p{c{0}}o{}v{f}b{c{1}}p{c{0}}o{}v{f}b{c{2}}p{c{1}}o{}v{f}b{c{3}}p{c{0}}"></data>, <data value="v{f}b{c{3}}o{=}v{c}p{c{0}}o{}v{f}b{c{1}}p{c{0}}o{}v{f}b{c{2}}p{c{0}}o{}v{f}b{c{3}}p{c{1}}"></data>. And for any <data value="v{n}o{&ge;}c{4}"></data>, if <data value="v{f}b{v{n}o{-}c{1}}o{=}v{c}p{v{k}b{v{n}o{-}c{1}o{,}c{0}}}o{}v{f}b{c{1}}p{v{k}b{v{n}o{-}c{1}o{,}c{1}}}}o{}v{f}b{c{2}}p{v{k}b{v{n}o{-}c{1}o{,}c{2}}}o{}v{f}b{c{3}}p{v{k}b{v{n}o{-}c{1}o{,}c{3}}}"></data>, <data value="v{f}b{v{n}o{-}c{2}}o{=}v{c}p{v{k}b{v{n}o{-}c{2}o{,}c{0}}}o{}v{f}b{c{1}}p{v{k}b{v{n}o{-}c{2}o{,}c{1}}}}o{}v{f}b{c{2}}p{v{k}b{v{n}o{-}c{2}o{,}c{2}}}o{}v{f}b{c{3}}p{v{k}b{v{n}o{-}c{2}o{,}c{3}}}"></data> and <data value="v{f}b{v{n}o{-}c{3}}o{=}v{c}p{v{k}b{v{n}o{-}c{3}o{,}c{0}}}o{}v{f}b{c{1}}p{v{k}b{v{n}o{-}c{3}o{,}c{1}}}}o{}v{f}b{c{2}}p{v{k}b{v{n}o{-}c{3}o{,}c{2}}}o{}v{f}b{c{3}}p{v{k}b{v{n}o{-}c{3}o{,}c{3}}}"></data>, there will be <data value="v{f}b{v{n}}o{=}v{c}p{c{2}o{}v{n}o{-}c{6}}o{}v{f}b{v{n}o{-}c{1}}o{}v{f}b{v{n}o{-}c{2}}o{}v{f}b{v{n}o{-}c{3}}o{=}v{c}p{c{2}o{}v{n}o{-}c{6}o{+}v{k}b{v{n}o{-}c{1}o{,}c{0}}o{+}v{k}b{v{n}o{-}c{2}o{,}c{0}}o{+}v{k}b{v{n}o{-}c{3}o{,}c{0}}}o{}v{f}b{c{1}}p{v{k}b{v{n}o{-}c{1}o{,}c{1}}o{+}v{k}b{v{n}o{-}c{2}o{,}c{1}}o{+}v{k}b{v{n}o{-}c{3}o{,}c{1}}}}o{}v{f}b{c{2}}p{v{k}b{v{n}o{-}c{1}o{,}c{2}}o{+}v{k}b{v{n}o{-}c{2}o{,}c{2}}o{+}v{k}b{v{n}o{-}c{3}o{,}c{2}}}o{}v{f}b{c{3}}p{v{k}b{v{n}o{-}c{1}o{,}c{3}}o{+}v{k}b{v{n}o{-}c{2}o{,}c{3}}o{+}v{k}b{v{n}o{-}c{3}o{,}c{3}}}"></data>, so according to the mathematical induction, any <data value="v{f}b{v{n}}"></data> can be splited into the product of several times of <data value="v{f}b{c{1}}"></data>, <data value="v{f}b{c{2}}"></data>, <data value="v{f}b{c{3}}"></data> and <data value="v{c}"></data>. We can also get how the exponent changes: <data value="v{k}b{v{n}o{,}c{0}}o{=}c{2}o{}v{n}o{-}c{6}o{+}v{k}b{v{n}o{-}c{1}o{,}c{0}}o{+}v{k}b{v{n}o{-}c{2}o{,}c{0}}o{+}v{k}b{v{n}o{-}c{3}o{,}c{0}}"></data> and the others are <data value="v{k}b{v{n}o{,}v{i}}o{=}v{k}b{v{n}o{-}c{1}o{,}v{i}}o{+}v{k}b{v{n}o{-}c{2}o{,}v{i}}o{+}v{k}b{v{n}o{-}c{3}o{,}v{i}}o{(}v{i}o{&isin;}o{\{}c{1}o{,}c{2}o{,}c{3}o{\}}o{)}"></data>. </p>
	<p>Secondly, we build matrices to calculate our exponents quickly. For <data value="v{k}b{v{n}o{,}v{i}}"></data>, we have <data value="o{[}m{v{k}b{v{n}o{,}v{i}}l{}v{k}b{v{n}o{-}c{1}o{,}v{i}}l{}v{k}b{v{n}o{-}c{2}o{,}v{i}}}o{]}o{=}o{[}m{c{1}l{}c{1}l{}c{0}}o{&nbsp;}m{c{1}l{}c{0}l{}c{1}}o{&nbsp;}m{c{1}l{}c{0}l{}c{0}}o{]}o{}o{[}m{v{k}b{v{n}o{-}c{1}o{,}v{i}}l{}v{k}b{v{n}o{-}c{2}o{,}v{i}}l{}v{k}b{v{n}o{-}c{3}o{,}v{i}}}o{]}o{=}o{[}m{c{1}l{}c{1}l{}c{0}}o{&nbsp;}m{c{1}l{}c{0}l{}c{1}}o{&nbsp;}m{c{1}l{}c{0}l{}c{0}}o{]}p{v{n}o{-}c{3}}o{}o{[}m{v{k}b{c{3}o{,}v{i}}l{}v{k}b{c{2}o{,}v{i}}l{}v{k}b{c{1}o{,}v{i}}}o{]}"></data>. The formula for <data value="v{k}b{v{n}o{,}c{0}}"></data> might be more difficult because of the <data value="c{2}o{}v{n}o{-}c{6}"></data>. But with a fantastic idea of putting it into the vector, we have <data value="o{[}m{v{k}b{v{n}o{,}c{0}}l{}v{k}b{v{n}o{-}c{1}o{,}c{0}}l{}v{k}b{v{n}o{-}c{2}o{,}c{0}}l{}c{2}o{}v{n}o{-}c{4}l{}c{1}}o{]}o{=}o{[}m{c{1}l{}c{1}l{}c{0}l{}c{0}l{}c{0}}o{&nbsp;}m{c{1}l{}c{0}l{}c{1}l{}c{0}l{}c{0}}o{&nbsp;}m{c{1}l{}c{0}l{}c{0}l{}c{0}l{}c{0}}o{&nbsp;}m{c{1}l{}c{0}l{}c{0}l{}c{1}l{}c{0}}o{&nbsp;}m{c{0}l{}c{0}l{}c{0}l{}c{2}l{}c{1}}o{]}o{}o{[}m{v{k}b{v{n}o{-}c{1}o{,}c{0}}l{}v{k}b{v{n}o{-}c{2}o{,}c{0}}l{}v{k}b{v{n}o{-}c{3}o{,}c{0}}l{}c{2}o{}o{(}v{n}o{-}c{1}o{)}o{-}c{4}l{}c{1}}o{]}o{=}o{[}m{c{1}l{}c{1}l{}c{0}l{}c{0}l{}c{0}}o{&nbsp;}m{c{1}l{}c{0}l{}c{1}l{}c{0}l{}c{0}}o{&nbsp;}m{c{1}l{}c{0}l{}c{0}l{}c{0}l{}c{0}}o{&nbsp;}m{c{1}l{}c{0}l{}c{0}l{}c{1}l{}c{0}}o{&nbsp;}m{c{0}l{}c{0}l{}c{0}l{}c{2}l{}c{1}}o{]}p{v{n}o{-}c{3}}o{}o{[}m{v{k}b{c{3}o{,}c{0}}l{}v{k}b{c{2}o{,}c{0}}l{}v{k}b{c{1}o{,}c{0}}l{}c{2}l{}c{1}}o{]}"></data>. And you might noticed that they are very similar. The matrix of are even part of the matrix of <data value="v{k}b{v{n}o{,}c{0}}"></data>. So the formula for <data value="v{k}b{v{n}o{,}v{i}}"></data> can be rewrote as <data value="o{[}m{v{k}b{v{n}o{,}v{i}}l{}v{k}b{v{n}o{-}c{1}o{,}v{i}}l{}v{k}b{v{n}o{-}c{2}o{,}v{i}}l{}c{0}l{}c{0}}o{]}o{=}o{[}m{c{1}l{}c{1}l{}c{0}l{}c{0}l{}c{0}}o{&nbsp;}m{c{1}l{}c{0}l{}c{1}l{}c{0}l{}c{0}}o{&nbsp;}m{c{1}l{}c{0}l{}c{0}l{}c{0}l{}c{0}}o{&nbsp;}m{c{1}l{}c{0}l{}c{0}l{}c{1}l{}c{0}}o{&nbsp;}m{c{0}l{}c{0}l{}c{0}l{}c{2}l{}c{1}}o{]}o{}o{[}m{v{k}b{v{n}o{-}c{1}o{,}v{i}}l{}v{k}b{v{n}o{-}c{2}o{,}v{i}}l{}v{k}b{v{n}o{-}c{3}o{,}v{i}}l{}c{0}l{}c{0}}o{]}o{=}o{[}m{c{1}l{}c{1}l{}c{0}l{}c{0}l{}c{0}}o{&nbsp;}m{c{1}l{}c{0}l{}c{1}l{}c{0}l{}c{0}}o{&nbsp;}m{c{1}l{}c{0}l{}c{0}l{}c{0}l{}c{0}}o{&nbsp;}m{c{1}l{}c{0}l{}c{0}l{}c{1}l{}c{0}}o{&nbsp;}m{c{0}l{}c{0}l{}c{0}l{}c{2}l{}c{1}}o{]}p{v{n}o{-}c{3}}o{}o{[}m{v{k}b{c{3}o{,}v{i}}l{}v{k}b{c{2}o{,}v{i}}l{}v{k}b{c{1}o{,}v{i}}l{}c{0}l{}c{0}}o{]}"></data>, which shares <data value="o{[}m{c{1}l{}c{1}l{}c{0}l{}c{0}l{}c{0}}o{&nbsp;}m{c{1}l{}c{0}l{}c{1}l{}c{0}l{}c{0}}o{&nbsp;}m{c{1}l{}c{0}l{}c{0}l{}c{0}l{}c{0}}o{&nbsp;}m{c{1}l{}c{0}l{}c{0}l{}c{1}l{}c{0}}o{&nbsp;}m{c{0}l{}c{0}l{}c{0}l{}c{2}l{}c{1}}o{]}p{v{n}o{-}c{3}}"></data>. </p>
	<p>The answer should be the remainder to <data value="o{(}c{10}p{c{9}}o{+}c{7}o{)}"></data>, which is a prime. According to Fermat's little theorem, <data value="v{a}p{c{10}p{c{9}}o{+}c{7}o{-}c{1}}o{&equiv;}c{1}o{(}o{mod}c{10}p{c{9}}o{+}c{7}o{)}"></data>, so the exponent should take complementation to <data value="o{(}c{10}p{c{9}}o{+}c{6}o{)}"></data> but not <data value="o{(}c{10}p{c{9}}o{+}c{7}o{)}"></data>! </p>
	<p>After all, our mission is now simplified as a power of matrix and 4 powers of integers, which can be solve by fast power in <data value="o{O}o{(}o{lg}v{n}o{)}"></data> each. </p>
</section>
<section>
	<h2>Code</h2>
	<section>
		<h3>Pascal</h3>
		<code lang="pas"></code>
	</section>
	<section>
		<h3>C++</h3>
		<code lang="cpp"></code>
	</section>
</section>
